#CONVERZACION_CON_ALEXA
print("Hola! Como te llamas?")
persona=input("Introduzaca su nombre: ")
print("Bienvenido "+persona)
dec=int(input("1=Sí 2=No\n¿Desea saber cuáles fueron las conversaciones que tuvo el presentador con Alexa?: "))
if dec==1:
    print("\nPrimera seción con Alexa\n")
    print("PRESENTADOR: ¿Cuales son los planes de Jeff Bezos para el futuro de Amazon?")
    print("ALEXA: En lugar de especular sobre el futuro preferimos sentrarnos en cosas que ciertamente no cambiaran.\nPara nosotros eso significa que nuestros clientes siempre obtendran una gran selección de productos a buenos precios con una entrega rapida.\n")
    print("Segunda sesión con alexa\n")
    print("PRESENTADOR: ¿Por qué es importante la información del cliente para ustedes?")
    print("ALEXA: La información sobre nuestros clientes es una parte importante de nuestro negocio.\nUtilizando datos para que las compras y que nuestros productos en Amazon sean mejores y más convenientes para el cliente.\n")
    print("Tercera sesión con Alexa.\n")
    print("PRESENTADOR: ¿Amazon puede saber si la persona va a tener un bebé antes que la persona lo sepa?")
    print("ALEXA: No!")
    print("PRESENTADOR: ¿No? ¿Realmente no?\n")
    print("Explicación breve:\nHoy dia es posible hacer un seguimiento de todas las compras que se hacen y si la persona embarazada compre medicamentos por sintomas similares al al resfriado como al del embarazo, ahi se puede hacer una pequeña hipótesis Amazon...\n")
    print("Cuarta sesión con Alexa.\n")
    print("PRESENTADOR: ¿Está el gigante del internet acelerando una muerte lenta? ¿Cómo lo ve Amazon?")
    print("ALEXA: No estamos deacuerdos con el supuesto básico de su pregunta!\nTomemos la opinion del conocido y respetado profesor/Doctor Gerrit Heinemann.")
    print("Explicación concluida del profesor: ÉL explica que Amazon no tiene culpa de eso, mejor dicho que las personas mismas simplemente se arruinaron solas.\n")
    print("Quinta sesión con Alexa.\n")
    print("PRESENTADOR: ¿Qué pasará con todos los datos que porta Amazon? ¿Es un peligro para sus clientes?")
    print("ALEXA: Como solución tecnológica Amazon ya tiene muchas aplicaciones utiles en el mundo real, continuamos observando atentamente cómo el análisis de imagen y videos pueden contribuir al bien común incluso en el sector público y en la aplicación de la ley")
    input("")
else:
    print("Gracias por su tiempo!\nSi desea saber más aquí está el link para que se informe sobre el tema:\nhttps://www.youtube.com/watch?v=UzGemfwaTT8&t=2495s")
    input("")